# Generated by Django 6.0 on 2025-12-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='physicalperson',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
