# Generated by Django 6.0 on 2025-12-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_create_consumidor_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalperson',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_person', to='customers.client'),
        ),
        migrations.AlterField(
            model_name='physicalperson',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_person', to='customers.client'),
        ),
    ]
