# Generated by Django 6.0 on 2025-12-27 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('allows_installments', models.BooleanField(default=False)),
                ('max_installments', models.PositiveIntegerField(default=1)),
                ('term_days', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
