# Generated by Django 6.0 on 2025-12-26 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brands.brands')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.categorie')),
            ],
        ),
    ]
